### PR TITLE
kmanc fix download command

### PR DESCRIPTION
**Pull request by kmanc**
#### Describe the purpose of the pull request

download command not working on evil-winrm 3.4

Lines 59 - 89 in the currently released version re-define the download function from [line 65 of winrm-fs](https://github.com/WinRb/winrm-fs/blob/fc98d6d182f966f2bf803f6fbfa7c99ac88ccebb/lib/winrm-fs/file_manager.rb#L65) with an additional parameter and check on lines 74 - 76, but for some reason that doesn't work. I'm not entirely sure if it is because of the check on lines 74 - 76 or if the FileManager class would also need to re-define [_putput_from_file](https://github.com/WinRb/winrm-fs/blob/fc98d6d182f966f2bf803f6fbfa7c99ac88ccebb/lib/winrm-fs/file_manager.rb#L88) in order to work, but when I remove this class definition locally the download command starts working again

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Hello. Weird... download works for me. Is not working for you? Did you try using absolute paths?

Anyway, this PR is outdated... our version in dev branch is 3.5 so your version should be 3.5 and is 3.4 ¿? you should clone the repo and PR should be dev to our dev branch... not master to our dev branch.

In your commit I can see just a removal of code for the redefinition of the function. So you are just suggesting to use download method from the WinRM library and that's all. Is that what you are suggesting?

**Comment by OscarAkaElvis** [comment]
I did some checks... it's true that the download feature is not working well at 100% as we can see in the next image

image

But I tried with your changes and same result!

image

As I said, it works fine using absolute paths:

image

**Comment by kmanc** [comment]
> Hello. Weird... download works for me. Is not working for you? Did you try using absolute paths?
> 
> Anyway, this PR is outdated... our version in dev branch is 3.5 so your version should be 3.5 and is 3.4 ¿? you should clone the repo and PR should be dev to our dev branch... not master to our dev branch.
> 
> In your commit I can see just a removal of code for the redefinition of the function. So you are just suggesting to use download method from the WinRM library and that's all. Is that what you are suggesting?

Oh whoops my bad, let me bring down the dev branch. But basically yes, that was what I was suggesting, to just use the WinRM library's function



> I did some checks... it's true that the download feature is not working well at 100% as we can see in the next image
> 
> image
> 
> But I tried with your changes and same result!
> 
> image
> 
> As I said, it works fine using absolute paths:
> 
> image

Interesting, I'll take a quick look at this today. I never tried full paths for both the source and destination, only the destination so that might have been my problem. Although when I used WinRM's download it worked on the first try with relative paths. Anyways I'll take this back to the drawing board and see if I can diagnose the root cause a little better

**Comment by kmanc** [comment]
Lol I'm so confused. I'm switching back and forth between 3.4 and 3.5 - half the time they both work with relative paths, half the time 3.4 doesn't work. I don't really know Ruby so I'm not super sure what the issue is but I guess it's safe to say that relative paths sometimes won't work, and full paths for both src and dest are preferred
